# Generated by Django 5.1.7 on 2025-03-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AplikacjaFilmyWeb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
