# Generated by Django 5.1.7 on 2025-03-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AplikacjaFilmyWeb', '0002_alter_film_description_alter_film_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='year',
            field=models.PositiveIntegerField(default=2014),
        ),
    ]
