# Generated by Django 5.1.7 on 2025-04-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AplikacjaFilmyWeb', '0003_film_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='poster',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
