# Generated by Django 5.1.7 on 2025-04-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AplikacjaFilmyWeb', '0004_film_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.PositiveSmallIntegerField(default=0)),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'Horror'), (2, 'Komedia'), (3, 'Sci-fi'), (4, 'Dramat'), (0, 'Inne')], default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.ImageField(blank=True, upload_to='posters'),
        ),
    ]
