# Generated by Django 5.1.7 on 2025-04-06 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AplikacjaFilmyWeb', '0005_additionalinfo_alter_film_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='additional',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AplikacjaFilmyWeb.additionalinfo'),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Horror'), (3, 'Sci-fi'), (4, 'Dramat'), (0, 'Inne'), (2, 'Komedia')], default=0),
        ),
    ]
