# Generated by Django 5.1.7 on 2025-04-06 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AplikacjaFilmyWeb', '0006_film_additional_alter_additionalinfo_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Sci-fi'), (4, 'Dramat'), (1, 'Horror'), (0, 'Inne'), (2, 'Komedia')], default=0),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, default=10.0, max_digits=4)),
                ('description', models.TextField(max_length=300)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AplikacjaFilmyWeb.film')),
            ],
        ),
    ]
