# Generated by Django 5.1.7 on 2025-04-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AplikacjaFilmyWeb', '0007_alter_additionalinfo_category_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Inne'), (2, 'Komedia'), (1, 'Horror'), (3, 'Sci-fi'), (4, 'Dramat')], default=0),
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=54)),
                ('film', models.ManyToManyField(to='AplikacjaFilmyWeb.film')),
            ],
        ),
    ]
